### ISSUE TITLE
pulling my head - Maximum call stack size exceeded

### ISSUE THREAD

**Issue by orefalo** [IlyaSemenov/objection-graphql-resolver#3]
Hi, thank you for this great library.

I am having issues compiling.

I narrowed the error below to this piece of code:

```
import { IdentificationModel } from 'db/models/model.identification'
import { GraphResolver, ModelResolver } from 'objection-graphql-resolver'

export function identityResolver(parent, args, ctx, info) {
	const resolveGraph = GraphResolver({
		// Map GraphQL types to model resolvers
		Identitication: ModelResolver(IdentificationModel, {
			// List fields that can be accessed via GraphQL
			fields: {
				id: true,
				identifier: true,
				type: true,
				expiration: true
			}
		})
	})

	const q = IdentificationModel.query()
	return resolveGraph(ctx, info, q)
}
```

If I comment this code, ... I don't get the error below.
This is so weird... any idea?

RangeError: Maximum call stack size exceeded
    at recursiveTypeRelatedTo (/Users/orefalo/.local/share/nvm/v14.17.0/lib/node_modules/typescript/lib/tsc.js:50861:44)
    at isRelatedTo (/Users/orefalo/.local/share/nvm/v14.17.0/lib/node_modules/typescript/lib/tsc.js:50530:34)
    at checkTypeRelatedTo (/Users/orefalo/.local/share/nvm/v14.17.0/lib/node_modules/typescript/lib/tsc.js:50216:26)
    at isTypeRelatedTo (/Users/orefalo/.local/share/nvm/v14.17.0/lib/node_modules/typescript/lib/tsc.js:50179:24)
    at isTypeAssignableTo (/Users/orefalo/.local/share/nvm/v14.17.0/lib/node_modules/typescript/lib/tsc.js:49470:20)
    at getSimplifiedConditionalType (/Users/orefalo/.local/share/nvm/v14.17.0/lib/node_modules/typescript/lib/tsc.js:48225:47)
    at getSimplifiedType (/Users/orefalo/.local/share/nvm/v14.17.0/lib/node_modules/typescript/lib/tsc.js:48161:41)
    at getNormalizedType (/Users/orefalo/.local/share/nvm/v14.17.0/lib/node_modules/typescript/lib/tsc.js:50192:57)

**Comment by IlyaSemenov** [comment]
That's your node and Typescript version?
